// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLmJp69fzEKU_BjE875sbZ9JTFqFDlZw',
    appId: '1:1019884858410:web:baf695f6be47400ce8a753',
    messagingSenderId: '1019884858410',
    projectId: 'mycoffee-c5ddb',
    authDomain: 'mycoffee-c5ddb.firebaseapp.com',
    storageBucket: 'mycoffee-c5ddb.firebasestorage.app',
    measurementId: 'G-5LCZSG8SRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWrIrHdioPaaWPqk0BWU0109qS5OWai4',
    appId: '1:1019884858410:android:64f1f03f4781bb48e8a753',
    messagingSenderId: '1019884858410',
    projectId: 'mycoffee-c5ddb',
    storageBucket: 'mycoffee-c5ddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZT9atej3wWuiAayMVuDeFnZR-pmIUVbo',
    appId: '1:1019884858410:ios:b8b72721b8c36068e8a753',
    messagingSenderId: '1019884858410',
    projectId: 'mycoffee-c5ddb',
    storageBucket: 'mycoffee-c5ddb.firebasestorage.app',
    iosBundleId: 'com.example.myCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPLmJp69fzEKU_BjE875sbZ9JTFqFDlZw',
    appId: '1:1019884858410:web:150d1d89600c50fae8a753',
    messagingSenderId: '1019884858410',
    projectId: 'mycoffee-c5ddb',
    authDomain: 'mycoffee-c5ddb.firebaseapp.com',
    storageBucket: 'mycoffee-c5ddb.firebasestorage.app',
    measurementId: 'G-4GMTJDBW88',
  );
}
